name: CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scully Publish
        # You may pin to the exact commit or the version.
        # uses: cmgriffing/scully-gh-pages-action@089c8e948312fa3ad94d1ebc9d763df442c839a8
        uses: cmgriffing/scully-gh-pages-action@v9
        with:
          # A personal access token needed to push your site after it has been built.
          access-token: ${{ secrets.ACCESS_TOKEN }}
          # The branch expected by GitHub to have the static files needed for your site.
          deploy-branch: production # optional, default is master
          # Additional arguments that get passed to `npm run build`.
          #build-args: # optional, default is 
          # Additional arguments that get passed to `npm run scully`.
          #scully-args: # optional, default is 
    
